ALTER TABLE posts ADD COLUMN reply_prompt TEXT;
ALTER TABLE posts ADD COLUMN silence_soul INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN silence_page INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN silence_knowledge INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN silence_restrictions INTEGER NOT NULL DEFAULT 0;
